USB_VID = 0x1209
USB_PID = 0x1DFF
USB_PRODUCT = "ODT Branch51"
USB_MANUFACTURER = "Oak Development Tech"

CHIP_VARIANT = SAMD51P19A
CHIP_FAMILY = samd51

INTERNAL_FLASH_FILESYSTEM = 1
LONGINT_IMPL = MPZ

CIRCUITPY_FULL_BUILD = 0
CIRCUITPY_FLOPPYIO = 0
CIRCUITPY_GIFIO = 0
CIRCUITPY_JPEGIO = 0
CIRCUITPY_SYNTHIO = 0
CIRCUITPY_KEYPAD = 1
CIRCUITPY_KEYPAD_SHIFTREGISTERKEYS = 0
CIRCUITPY_KEYPAD_KEYMATRIX = 0
CIRCUITPY_ROTARYIO = 0
CIRCUITPY_PS2IO = 0

# Override optimization to keep binary small
OPTIMIZATION_FLAGS = -Os